## Numpy

In [7]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.random.rand(5)

array([0.38010365, 0.24396958, 0.85690992, 0.26542569, 0.41595608])

In [13]:
np.random.rand(5,5)

array([[0.34884584, 0.51592783, 0.10073185, 0.10661731, 0.55319679],
       [0.28782015, 0.85560514, 0.1658738 , 0.87573168, 0.78599171],
       [0.55355148, 0.37121975, 0.57765053, 0.33868311, 0.3643973 ],
       [0.18148814, 0.39866855, 0.81193356, 0.92225515, 0.00856642],
       [0.24653322, 0.34604028, 0.74933863, 0.60554826, 0.89168413]])

In [15]:
np.random.randn(2) #dousy dostribution from normal distribution

array([ 1.16108953, -1.17520618])

In [17]:
np.random.randint(1,100,10)

array([34, 68, 17, 72, 16, 37, 67, 93, 39, 81])

In [19]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])