# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_arr = arr[0:6]

In [13]:
slice_arr[:]

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_arr[:] = 99

In [15]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy() #need to creat a copy not the affect the orginal arr while using numpy 

In [18]:
arr_copy[:]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:] = 100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2D ARRAY

In [23]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[2,1]

40

In [28]:
arr_2d[1][2]

30

In [29]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [30]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [31]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

## Conditional Selection

In [32]:
arr = np.arange(1,11)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
bool_arr = arr > 5

In [36]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [37]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [38]:
arr[arr<3]

array([1, 2])

In [39]:
arr_2d = np.arange(50).reshape(5,10)

In [40]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [43]:
arr_2d[4:, ]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])